### ISSUE TITLE
2.0.30 has a dependency to MW > 1.42

### ISSUE THREAD

**Issue by YOUR1** [hallowelt/mwstake-mediawiki-component-commonwebapis#25]
Specific line: https://github.com/hallowelt/mwstake-mediawiki-component-commonwebapis/blob/fffb29894a53b09a61c41088ec3a0fb01ffb0085/src/Data/UserQueryStore/PrimaryDataProvider.php#L96

That's not correct, 2.x should be compatible with 1.39, as mentioned on packagist.

**Comment by YOUR1** [comment]
@osnard or @it-spiderman can somebody check this asap?

**Comment by osnard** [comment]
Thanks for reporting. I'll check.

**Comment by osnard** [comment]
Should be fixed with release `2.0.31`. Release `3.0.0` is now documented to require MediaWiki 1.43 (not released yet).
