### ISSUE TITLE
Uncaught Error: Call to undefined function OOJSPlus

### ISSUE THREAD

**Issue by krabina** [hallowelt/mwstake-mediawiki-component-commonwebapis#6]
When trying to install the extension on MW 1.35, I get the following error.

`Fatal error: Uncaught Error: Call to undefined function OOJSPlus\mwsInitComponents() in extensions/OOJSPlus/src/Extension.php:7 Stack trace: #0 1.35.8/includes/registration/ExtensionRegistry.php(578): OOJSPlus\Extension::callback() #1 1.35.8/includes/registration/ExtensionRegistry.php(261): ExtensionRegistry->exportExtractedData() #2 1.35.8/includes/Setup.php(161): ExtensionRegistry->loadFromQueue() #3 1.35.8/includes/WebStart.php(89): require_once('1...') #4 1.35.8/index.php(44): require('1...') #5 {main} thrown in extensions/OOJSPlus/src/Extension.php on line 7`

**Comment by krabina** [comment]
I tried both the master branch and the REL1_35 branch

**Comment by osnard** [comment]
Did you use "Special:ExtensionDistributor" from mediawiki.org to download the extensions? Or did you install using composer?

**Comment by krabina** [comment]
I used git

**Comment by krabina** [comment]
Indeed, downloading with extension distributor works! Thank you!

**Comment by osnard** [comment]
Great! If you use git, you may need to manually run `composer update` in the respective extension directory. But this is not recommended.
